/**
 * Mirrored from opensips-docs-collector/src/schemas/collection-state.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';

const PhaseStatusSchema = z.object({
  status: z.enum(['pending', 'in_progress', 'completed', 'failed']),
  completedAt: z.string().datetime().optional(),
  result: z.any().optional(),
});

/**
 * @description Schema for tracking batch extraction progress within a section.
 * Used for batched extraction of large sections (e.g., parameters, functions).
 */
const BatchStatusSchema = z.object({
  batchIndex: z.number().describe('Zero-based batch index'),
  itemNames: z.array(z.string()).describe('Names of items in this batch'),
  status: z.enum(['pending', 'in_progress', 'completed', 'failed']),
  data: z.any().optional().describe('Cached extraction result for this batch'),
  error: z.string().optional(),
  completedAt: z.string().datetime().optional(),
});

/**
 * @description Schema for tracking individual section status within a module.
 * Used for section-based module extraction to enable granular retry.
 * Extended with batch tracking for large sections like parameters and functions.
 */
const SectionStatusSchema = z.object({
  status: z.enum(['pending', 'in_progress', 'completed', 'failed']),
  error: z.string().optional(),
  attempts: z.number().default(0),
  lastAttempt: z.string().datetime().optional(),
  /**
   * @description Discovered item names for batched extraction (e.g., parameter names).
   * Populated during the discovery phase before batch extraction.
   */
  discoveredItems: z.array(z.string()).optional(),
  /**
   * @description Batch tracking for large sections.
   * Each batch contains a subset of items to extract.
   */
  batches: z.array(BatchStatusSchema).optional(),
  /**
   * @description Number of items per batch (default: 5).
   */
  batchSize: z.number().optional(),
  /**
   * @description Whether batched extraction is enabled for this section.
   */
  useBatchedExtraction: z.boolean().optional(),
});

const ItemStatusSchema = z.object({
  status: z.enum(['pending', 'in_progress', 'completed', 'failed']),
  filePath: z.string().optional(),
  error: z.string().optional(),
  attempts: z.number(),
  lastAttempt: z.string().datetime().optional(),
  /**
   * @description Section-level status tracking for module extraction.
   * Keys are section names: overview, parameters, functions, mi, statistics, events, pvars, examples
   */
  sections: z.record(z.string(), SectionStatusSchema).optional(),
});

const ModulesPhaseSchema = PhaseStatusSchema.extend({
  total: z.number(),
  completed: z.number(),
  failed: z.number(),
  items: z.record(z.string(), ItemStatusSchema),
});

const CorePhaseSchema = PhaseStatusSchema.extend({
  items: z.record(z.string(), ItemStatusSchema),
});

const GuidesPhaseSchema = PhaseStatusSchema.extend({
  items: z.record(z.string(), ItemStatusSchema),
});

const ErrorEntrySchema = z.object({
  phase: z.string(),
  item: z.string(),
  error: z.string(),
  timestamp: z.string().datetime(),
  retryCount: z.number(),
});

export const CollectionStateSchema = z.object({
  version: z.string(),
  startedAt: z.string().datetime(),
  lastUpdatedAt: z.string().datetime(),
  status: z.enum(['pending', 'in_progress', 'completed', 'failed']),
  
  phases: z.object({
    discovery: PhaseStatusSchema,
    modules: ModulesPhaseSchema,
    core: CorePhaseSchema,
    guides: GuidesPhaseSchema,
    enhancement: PhaseStatusSchema,
    consolidation: PhaseStatusSchema,
  }),
  
  errors: z.array(ErrorEntrySchema),
});

export type CollectionState = z.infer<typeof CollectionStateSchema>;
export type BatchStatus = z.infer<typeof BatchStatusSchema>;
export type SectionStatus = z.infer<typeof SectionStatusSchema>;
export type ItemStatus = z.infer<typeof ItemStatusSchema>;
export type ErrorEntry = z.infer<typeof ErrorEntrySchema>;