/**
 * Mirrored from opensips-docs-collector/src/schemas/guides.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "./base.schema.js";

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const InstallStepSchema = z.object({
  step_number: z.number(),
  title: z.string(),
  description: z.string(),
  commands: z.array(z.string()),
  notes: z.string().optional(),
});

const ConfigSectionSchema = z.object({
  section_name: z.string(),
  description: z.string(),
  parameters: z.array(z.string()),
  examples: z.array(CodeExampleSchema),
});

const PrerequisiteSchema = z.object({
  name: z.string(),
  description: z.string(),
  required: z.boolean(),
});

const TroubleshootingItemSchema = z.object({
  problem: z.string(),
  solution: z.string(),
});

const BestPracticeSchema = z.object({
  title: z.string(),
  description: z.string(),
});

export const GuideDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.enum(["installation_guide", "configuration_guide", "syntax_guide"]),

  // Installation Specific
  installation_steps: z.array(InstallStepSchema).optional(),
  prerequisites: z.array(PrerequisiteSchema).optional(),
  troubleshooting: z.array(TroubleshootingItemSchema).optional(),

  // Configuration Specific
  configuration_sections: z.array(ConfigSectionSchema).optional(),
  best_practices: z.array(BestPracticeSchema).optional(),
});

export type GuideDocument = z.infer<typeof GuideDocumentSchema>;
