/**
 * Mirrored from opensips-docs-collector/src/schemas/modules.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';
import { BaseDocumentSchema } from './base.schema.js';

// Nested Schemas

const DependencySchema = z.object({
  name: z.string(),
  type: z.enum(['module', 'library', 'application']),
  reason: z.string().optional(),
  optional: z.boolean(),
});

const ModuleParameterSchema = z.object({
  name: z.string(),
  type: z.string().describe('Data type (e.g., "integer", "string")'),
  default_value: z.string().optional(),
  description: z.string(),
  possible_values: z.array(z.string()).optional(),
  valid_range_min: z.number().optional(),
  valid_range_max: z.number().optional(),
  scope: z.string().optional().describe('e.g., "global"'),
  example_value: z.string().optional(),
  example_code: z.string().optional().describe('Example usage code'),
  notes: z.string().optional(),
});

const FunctionParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  default: z.string().optional(),
  description: z.string(),
  valid_values: z.array(z.string()).optional(),
});

const ReturnValueSchema = z.object({
  value: z.string(),
  condition: z.string(),
});

const CodeExampleSchema = z.object({
  language: z.string().describe('Language identifier (e.g., "opensips", "bash")'),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const ModuleFunctionSchema = z.object({
  name: z.string(),
  signature: z.string().describe('Full function signature'),
  parameters: z.array(FunctionParameterSchema),
  return_type: z.string(),
  return_values: z.array(ReturnValueSchema).optional(),
  description: z.string(),
  usage_context: z.array(z.string()).describe('Routes where this function can be used'),
  examples: z.array(CodeExampleSchema),
  related_functions: z.array(z.string()).optional(),
  deprecated: z.boolean().optional(),
});

const MIParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  description: z.string(),
});

const MIReturnValueSchema = z.object({
  type: z.string(),
  description: z.string(),
  structure: z.any().optional(), // JSON schema or loose object
});

const MIFunctionSchema = z.object({
  name: z.string(),
  parameters: z.array(MIParameterSchema),
  return_value: MIReturnValueSchema.optional(),
  description: z.string(),
  examples: z.array(CodeExampleSchema),
});

const StatisticSchema = z.object({
  name: z.string(),
  type: z.enum(['counter', 'gauge', 'histogram']).optional().or(z.string()), // Flexible for extraction
  description: z.string(),
  access_methods: z.array(z.string()).optional(),
  reset_method: z.string().optional(),
});

const EventParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  description: z.string(),
});

const EventSchema = z.object({
  name: z.string(),
  description: z.string(),
  parameters: z.array(EventParameterSchema),
  subscribe_method: z.string().optional(),
  examples: z.array(CodeExampleSchema).optional(),
});

const PseudoVariableSchema = z.object({
  name: z.string(),
  type: z.string(),
  readable: z.boolean(),
  writable: z.boolean(),
  scope: z.string(),
  description: z.string(),
  possible_values: z.array(z.string()).optional(),
});

const ConfigExampleSchema = z.object({
  title: z.string(),
  description: z.string(),
  code: z.string(),
  explanation: z.string().optional(),
});

/**
 * Module Document Schema
 * Defines the structure for OpenSIPS Modules.
 */
export const ModuleDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal('module'),
  module_name: z.string(),
  overview: z.string(),
  how_it_works: z.string().nullable().optional(),
  dependencies_required: z.array(DependencySchema).nullable().optional(),
  dependencies_optional: z.array(z.string()).nullable().optional(),
  exported_parameters: z.array(ModuleParameterSchema),
  exported_functions: z.array(ModuleFunctionSchema),
  exported_mi_functions: z.array(MIFunctionSchema).optional(),
  exported_statistics: z.array(StatisticSchema).optional(),
  exported_events: z.array(EventSchema).optional(),
  exported_pseudo_variables: z.array(PseudoVariableSchema).optional(),
  configuration_examples: z.array(ConfigExampleSchema).optional(),
});

export type ModuleDocument = z.infer<typeof ModuleDocumentSchema>;
