/**
 * Mirrored from opensips-docs-collector/src/schemas/module-sections.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';

/**
 * Module Sections Schema
 * Defines partial schemas for section-based module extraction.
 * Each schema extracts a specific portion of the ModuleDocumentSchema.
 */

// ============================================================================
// Shared Nested Schemas (reused across sections)
// ============================================================================

/**
 * @description Represents a module dependency.
 */
export const DependencySchema = z.object({
  name: z.string(),
  type: z.enum(['module', 'library', 'application']),
  reason: z.string().optional(),
  optional: z.boolean(),
});

/**
 * @description Represents a module parameter configuration.
 */
export const ModuleParameterSchema = z.object({
  name: z.string(),
  type: z.string().describe('Data type (e.g., "integer", "string")'),
  default_value: z.string().optional(),
  description: z.string(),
  possible_values: z.array(z.string()).optional(),
  valid_range_min: z.number().optional(),
  valid_range_max: z.number().optional(),
  scope: z.string().optional().describe('e.g., "global"'),
  example_value: z.string().optional(),
  example_code: z.string().optional().describe('Example usage code'),
  notes: z.string().optional(),
});

/**
 * @description Represents a function parameter.
 */
export const FunctionParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  default: z.string().optional(),
  description: z.string(),
  valid_values: z.array(z.string()).optional(),
});

/**
 * @description Represents a function return value condition.
 */
export const ReturnValueSchema = z.object({
  value: z.string(),
  condition: z.string(),
});

/**
 * @description Represents a code example.
 */
export const CodeExampleSchema = z.object({
  language: z.string().describe('Language identifier (e.g., "opensips", "bash")'),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

/**
 * @description Represents an exported module function.
 */
export const ModuleFunctionSchema = z.object({
  name: z.string(),
  signature: z.string().describe('Full function signature'),
  parameters: z.array(FunctionParameterSchema),
  return_type: z.string(),
  return_values: z.array(ReturnValueSchema).optional(),
  description: z.string(),
  usage_context: z.array(z.string()).describe('Routes where this function can be used'),
  examples: z.array(CodeExampleSchema),
  related_functions: z.array(z.string()).optional(),
  deprecated: z.boolean().optional(),
});

/**
 * @description Represents an MI command parameter.
 */
export const MIParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  description: z.string(),
});

/**
 * @description Represents an MI command return value.
 */
export const MIReturnValueSchema = z.object({
  type: z.string(),
  description: z.string(),
  structure: z.any().optional(),
});

/**
 * @description Represents a Management Interface function.
 */
export const MIFunctionSchema = z.object({
  name: z.string(),
  parameters: z.array(MIParameterSchema),
  return_value: MIReturnValueSchema.optional(),
  description: z.string(),
  examples: z.array(CodeExampleSchema),
});

/**
 * @description Represents a module statistic.
 */
export const StatisticSchema = z.object({
  name: z.string(),
  type: z.enum(['counter', 'gauge', 'histogram']).optional().or(z.string()),
  description: z.string(),
  access_methods: z.array(z.string()).optional(),
  reset_method: z.string().optional(),
});

/**
 * @description Represents an event parameter.
 */
export const EventParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  description: z.string(),
});

/**
 * @description Represents a module event.
 */
export const EventSchema = z.object({
  name: z.string(),
  description: z.string(),
  parameters: z.array(EventParameterSchema),
  subscribe_method: z.string().optional(),
  examples: z.array(CodeExampleSchema).optional(),
});

/**
 * @description Represents a pseudo-variable exported by a module.
 */
export const PseudoVariableSchema = z.object({
  name: z.string(),
  type: z.string(),
  readable: z.boolean(),
  writable: z.boolean(),
  scope: z.string(),
  description: z.string(),
  possible_values: z.array(z.string()).optional(),
});

/**
 * @description Represents a configuration example.
 */
export const ConfigExampleSchema = z.object({
  title: z.string(),
  description: z.string(),
  code: z.string(),
  explanation: z.string().optional(),
});

// ============================================================================
// Section Schemas (partial schemas for focused extraction)
// ============================================================================

/**
 * @description Schema for extracting module overview section.
 * Includes: module_name, overview, how_it_works, dependencies
 */
export const ModuleOverviewSectionSchema = z.object({
  module_name: z.string().describe('Exact module name'),
  overview: z.string().describe('Module overview/synopsis'),
  how_it_works: z.string().nullable().optional().describe('Detailed explanation of module operation'),
  dependencies_required: z.array(DependencySchema).nullable().optional().describe('Required dependencies'),
  dependencies_optional: z.array(z.string()).nullable().optional().describe('Optional dependencies'),
});

/**
 * @description Schema for extracting module parameters section.
 * Includes: exported_parameters array
 */
export const ModuleParametersSectionSchema = z.object({
  exported_parameters: z.array(ModuleParameterSchema).describe('Module configuration parameters'),
});

/**
 * @description Schema for extracting module functions section.
 * Includes: exported_functions array
 */
export const ModuleFunctionsSectionSchema = z.object({
  exported_functions: z.array(ModuleFunctionSchema).describe('Exported script functions'),
});

/**
 * @description Schema for extracting MI commands section.
 * Includes: exported_mi_functions array (required but can be empty)
 * Note: Array is required for Anthropic API compatibility (rejects empty schemas)
 */
export const ModuleMISectionSchema = z.object({
  exported_mi_functions: z.array(MIFunctionSchema).describe('Management Interface commands (empty if none)'),
});

/**
 * @description Schema for extracting statistics section.
 * Includes: exported_statistics array (required but can be empty)
 * Note: Array is required for Anthropic API compatibility (rejects empty schemas)
 */
export const ModuleStatisticsSectionSchema = z.object({
  exported_statistics: z.array(StatisticSchema).describe('Runtime statistics (empty if none)'),
});

/**
 * @description Schema for extracting events section.
 * Includes: exported_events array (required but can be empty)
 * Note: Array is required for Anthropic API compatibility (rejects empty schemas)
 */
export const ModuleEventsSectionSchema = z.object({
  exported_events: z.array(EventSchema).describe('Module events (empty if none)'),
});

/**
 * @description Schema for extracting pseudo-variables section.
 * Includes: exported_pseudo_variables array (required but can be empty)
 * Note: Array is required for Anthropic API compatibility (rejects empty schemas)
 */
export const ModulePVarsSectionSchema = z.object({
  exported_pseudo_variables: z.array(PseudoVariableSchema).describe('Pseudo-variables (empty if none)'),
});

/**
 * @description Schema for extracting configuration examples section.
 * Includes: configuration_examples array (required but can be empty)
 * Note: Array is required for Anthropic API compatibility (rejects empty schemas)
 */
export const ModuleExamplesSectionSchema = z.object({
  configuration_examples: z.array(ConfigExampleSchema).describe('Configuration examples (empty if none)'),
});

// ============================================================================
// Discovery Schemas (for batched extraction)
// ============================================================================

/**
 * @description Schema for discovering parameter names without full extraction.
 * Used in the discovery phase of batched parameter extraction.
 * Lightweight - only extracts names, not full details.
 */
export const ParameterNamesDiscoverySchema = z.object({
  parameter_names: z.array(z.string()).describe('List of parameter names found in the documentation, in order of appearance'),
});

/**
 * @description Schema for discovering function names without full extraction.
 * Used in the discovery phase of batched function extraction.
 */
export const FunctionNamesDiscoverySchema = z.object({
  function_names: z.array(z.string()).describe('List of function names found in the documentation, in order of appearance'),
});

/**
 * @description Schema for batched parameter extraction.
 * Same as ModuleParametersSectionSchema but used with targeted prompts.
 */
export const ModuleParametersBatchSchema = z.object({
  exported_parameters: z.array(ModuleParameterSchema).describe('Extracted parameters for this batch'),
});

/**
 * @description Schema for batched function extraction.
 * Same as ModuleFunctionsSectionSchema but used with targeted prompts.
 */
export const ModuleFunctionsBatchSchema = z.object({
  exported_functions: z.array(ModuleFunctionSchema).describe('Extracted functions for this batch'),
});

// ============================================================================
// Type Exports
// ============================================================================

export type Dependency = z.infer<typeof DependencySchema>;
export type ModuleParameter = z.infer<typeof ModuleParameterSchema>;
export type FunctionParameter = z.infer<typeof FunctionParameterSchema>;
export type ReturnValue = z.infer<typeof ReturnValueSchema>;
export type CodeExample = z.infer<typeof CodeExampleSchema>;
export type ModuleFunction = z.infer<typeof ModuleFunctionSchema>;
export type MIParameter = z.infer<typeof MIParameterSchema>;
export type MIReturnValue = z.infer<typeof MIReturnValueSchema>;
export type MIFunction = z.infer<typeof MIFunctionSchema>;
export type Statistic = z.infer<typeof StatisticSchema>;
export type EventParameter = z.infer<typeof EventParameterSchema>;
export type Event = z.infer<typeof EventSchema>;
export type PseudoVariable = z.infer<typeof PseudoVariableSchema>;
export type ConfigExample = z.infer<typeof ConfigExampleSchema>;

export type ModuleOverviewSection = z.infer<typeof ModuleOverviewSectionSchema>;
export type ModuleParametersSection = z.infer<typeof ModuleParametersSectionSchema>;
export type ModuleFunctionsSection = z.infer<typeof ModuleFunctionsSectionSchema>;
export type ModuleMISection = z.infer<typeof ModuleMISectionSchema>;
export type ModuleStatisticsSection = z.infer<typeof ModuleStatisticsSectionSchema>;
export type ModuleEventsSection = z.infer<typeof ModuleEventsSectionSchema>;
export type ModulePVarsSection = z.infer<typeof ModulePVarsSectionSchema>;
export type ModuleExamplesSection = z.infer<typeof ModuleExamplesSectionSchema>;

// Discovery types for batched extraction
export type ParameterNamesDiscovery = z.infer<typeof ParameterNamesDiscoverySchema>;
export type FunctionNamesDiscovery = z.infer<typeof FunctionNamesDiscoverySchema>;
export type ModuleParametersBatch = z.infer<typeof ModuleParametersBatchSchema>;
export type ModuleFunctionsBatch = z.infer<typeof ModuleFunctionsBatchSchema>;

// ============================================================================
// Section Configuration (for workflow factory)
// ============================================================================

/**
 * @description Configuration for each module section workflow.
 */
export const MODULE_SECTIONS = [
  { name: 'overview', schemaType: 'ModuleOverviewSectionSchema', promptKey: 'module_overview', required: true },
  { name: 'parameters', schemaType: 'ModuleParametersSectionSchema', promptKey: 'module_parameters', required: true },
  { name: 'functions', schemaType: 'ModuleFunctionsSectionSchema', promptKey: 'module_functions', required: true },
  { name: 'mi', schemaType: 'ModuleMISectionSchema', promptKey: 'module_mi', required: false },
  { name: 'statistics', schemaType: 'ModuleStatisticsSectionSchema', promptKey: 'module_statistics', required: false },
  { name: 'events', schemaType: 'ModuleEventsSectionSchema', promptKey: 'module_events', required: false },
  { name: 'pvars', schemaType: 'ModulePVarsSectionSchema', promptKey: 'module_pvars', required: false },
  { name: 'examples', schemaType: 'ModuleExamplesSectionSchema', promptKey: 'module_examples', required: false },
] as const;

export type ModuleSectionName = typeof MODULE_SECTIONS[number]['name'];
