/**
 * Mirrored from opensips-docs-collector/src/schemas/core/events.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "../base.schema.js";

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const EventParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  description: z.string(),
});

const EventDefinitionSchema = z.object({
  name: z.string(),
  module: z.string(),
  description: z.string(),
  parameters: z.array(EventParameterSchema),
  subscribe_method: z.string(),
  examples: z.array(CodeExampleSchema),
});

export const EventDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal("event"),
  events: z.array(EventDefinitionSchema),
  event_interface_types: z.array(z.string()).optional(),
});

export type EventDocument = z.infer<typeof EventDocumentSchema>;
