/**
 * Mirrored from opensips-docs-collector/src/schemas/core/flags.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';
import { BaseDocumentSchema } from '../base.schema.js';

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const FlagFunctionSchema = z.object({
  name: z.string(),
  purpose: z.string(),
  signature: z.string(),
});

const FlagTypeSchema = z.object({
  type_name: z.string(),
  description: z.string(),
  max_flags: z.number(),
  persistence: z.string(),
  functions: z.array(FlagFunctionSchema),
  examples: z.array(CodeExampleSchema),
});

export const FlagDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal('flag'),
  flag_types: z.array(FlagTypeSchema),
});

export type FlagDocument = z.infer<typeof FlagDocumentSchema>;
