/**
 * Mirrored from opensips-docs-collector/src/schemas/core/functions.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';
import { BaseDocumentSchema } from '../base.schema.js';

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const FunctionParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  default: z.string().optional(),
  description: z.string(),
  valid_values: z.array(z.string()).optional(),
});

const CoreFunctionSchema = z.object({
  name: z.string(),
  signature: z.string(),
  parameters: z.array(FunctionParameterSchema),
  return_type: z.string(),
  description: z.string(),
  usage_context: z.array(z.string()),
  examples: z.array(CodeExampleSchema),
  category: z.string().optional(),
  related_functions: z.array(z.string()).optional(),
});

export const CoreFunctionDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal('core_function'),
  functions: z.array(CoreFunctionSchema),
  function_categories: z.array(z.string()).optional(),
});

export type CoreFunctionDocument = z.infer<typeof CoreFunctionDocumentSchema>;
