/**
 * Mirrored from opensips-docs-collector/src/schemas/core/mi-commands.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "../base.schema.js";

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const MIParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  description: z.string(),
});

const MIReturnValueSchema = z.object({
  type: z.string(),
  description: z.string(),
  structure: z.any().optional(),
});

const MICommandSchema = z.object({
  name: z.string(),
  description: z.string(),
  parameters: z.array(MIParameterSchema),
  return_value: MIReturnValueSchema.optional(),
  examples: z.array(CodeExampleSchema),
  available_in: z.array(z.string()).optional(),
});

export const MICommandDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal("mi_command"),
  mi_commands: z.array(MICommandSchema),
  mi_protocols: z.array(z.string()).optional(),
});

export type MICommandDocument = z.infer<typeof MICommandDocumentSchema>;
