/**
 * Mirrored from opensips-docs-collector/src/schemas/core/operators.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';
import { BaseDocumentSchema } from '../base.schema.js';

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const OperatorSchema = z.object({
  symbol: z.string(),
  name: z.string(),
  category: z.string(),
  operand_type: z.enum(['unary', 'binary', 'ternary']),
  description: z.string(),
  applicable_to: z.array(z.string()),
  precedence: z.number(),
  associativity: z.enum(['left', 'right']),
  examples: z.array(CodeExampleSchema),
});

export const OperatorDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal('operator'),
  operators: z.array(OperatorSchema),
  operator_categories: z.array(z.string()),
});

export type OperatorDocument = z.infer<typeof OperatorDocumentSchema>;
