/**
 * Mirrored from opensips-docs-collector/src/schemas/core/parameters.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "../base.schema.js";

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const CoreParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  default_value: z.string(),
  description: z.string(),
  syntax: z.string().optional(),
  multiple_allowed: z.boolean(),
  valid_values: z.array(z.string()).optional(),
  examples: z.array(CodeExampleSchema),
  category: z.string().optional(),
  notes: z.string().optional(),
});

export const CoreParameterDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal("core_parameter"),
  parameters: z.array(CoreParameterSchema),
  parameter_categories: z.array(z.string()).optional(),
});

export type CoreParameterDocument = z.infer<typeof CoreParameterDocumentSchema>;
