/**
 * Mirrored from opensips-docs-collector/src/schemas/core/routes.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';
import { BaseDocumentSchema } from '../base.schema.js';

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const RouteTypeSchema = z.object({
  name: z.string(),
  syntax: z.string(),
  description: z.string(),
  trigger_condition: z.string(),
  available_variables: z.array(z.string()).optional(),
  available_functions: z.array(z.string()).optional(),
  can_call_routes: z.boolean(),
  examples: z.array(CodeExampleSchema),
});

export const RouteDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal('route_type'),
  route_types: z.array(RouteTypeSchema),
});

export type RouteDocument = z.infer<typeof RouteDocumentSchema>;
