/**
 * Mirrored from opensips-docs-collector/src/schemas/core/statistics.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "../base.schema.js";

const StatisticDefinitionSchema = z.object({
  name: z.string(),
  module: z.string(),
  type: z.enum(["counter", "gauge"]),
  description: z.string(),
  access_methods: z.array(z.string()),
  reset_method: z.string().optional(),
});

export const StatisticDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal("statistic"),
  statistics: z.array(StatisticDefinitionSchema),
  statistic_access_methods: z.array(z.string()).optional(),
});

export type StatisticDocument = z.infer<typeof StatisticDocumentSchema>;
