/**
 * Mirrored from opensips-docs-collector/src/schemas/core/statements.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "../base.schema.js";

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const StatementParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  description: z.string(),
});

const StatementSchema = z.object({
  name: z.string(),
  syntax: z.string(),
  description: z.string(),
  parameters: z.array(StatementParameterSchema),
  usage_context: z.array(z.string()),
  examples: z.array(CodeExampleSchema),
  related_statements: z.array(z.string()).optional(),
});

export const StatementDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal("statement"),
  statements: z.array(StatementSchema),
});

export type StatementDocument = z.infer<typeof StatementDocumentSchema>;
