/**
 * Mirrored from opensips-docs-collector/src/schemas/core/transformations.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from 'zod';
import { BaseDocumentSchema } from '../base.schema.js';

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const TransformationParameterSchema = z.object({
  name: z.string(),
  type: z.string(),
  required: z.boolean(),
  description: z.string(),
});

const TransformationSchema = z.object({
  name: z.string(),
  class: z.string(),
  description: z.string(),
  syntax: z.string(),
  parameters: z.array(TransformationParameterSchema),
  input_type: z.string(),
  output_type: z.string(),
  examples: z.array(CodeExampleSchema),
  chainable: z.boolean(),
});

export const TransformationDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal('transformation'),
  transformations: z.array(TransformationSchema),
});

export type TransformationDocument = z.infer<typeof TransformationDocumentSchema>;
