/**
 * Mirrored from opensips-docs-collector/src/schemas/core/variables.schema.ts
 *
 * DO NOT EDIT THIS FILE. Schema changes flow downstream from the extraction
 * project. To update: change upstream, re-run the mirroring procedure, and
 * regenerate the schema hash via .
 *
 * Schema rationale: see docs/architecture/adr/004-node-typescript-build-stack.md
 * and docs/architecture/data-pipeline.md §5.3.
 */

import { z } from "zod";
import { BaseDocumentSchema } from "../base.schema.js";

const CodeExampleSchema = z.object({
  language: z.string(),
  code: z.string(),
  description: z.string(),
  context: z.string().optional(),
});

const VariableSubfieldSchema = z.object({
  name: z.string(),
  access_syntax: z.string(),
  description: z.string(),
  type: z.string(),
});

const CoreVariableSchema = z.object({
  name: z.string().describe("Variable notation e.g. $si"),
  alternate_names: z.array(z.string()).optional(),
  description: z.string(),
  type: z.string().describe("Data type returned"),
  readable: z.boolean(),
  writable: z.boolean(),
  scope: z.string().describe("Where available (e.g. message_context)"),
  context: z.enum(["request", "reply", "both"]),
  related_variables: z.array(z.string()).optional(),
  examples: z.array(CodeExampleSchema),
  notes: z.string().optional(),
  subfields: z.array(VariableSubfieldSchema).optional(),
  indexed: z.boolean().default(false),
  multi_value: z.boolean().default(false),
});

export const CoreVariableDocumentSchema = BaseDocumentSchema.extend({
  document_type: z.literal("core_variable"),
  variables: z.array(CoreVariableSchema),
  syntax_notes: z.string().optional(),
});

export type CoreVariableDocument = z.infer<typeof CoreVariableDocumentSchema>;
